const ADMIN_PERMISSIONS: { [key: string]: string } = {
    /* ADMIN related permissions */
    VIEW_ALL_ADMIN: "VIEW_ALL_ADMIN",
    CREATE_ADMIN: "CREATE_ADMIN",
    DELETE_ADMIN: "DELETE_ADMIN",
    UPDATE_ADMIN: "UPDATE_ADMIN",

    /* USER related permissions */
    VIEW_ALL_USERS: "VIEW_ALL_USERS",
    CREATE_USER: "CREATE_USER",

    /* BUSINESS_PROFILE related permissions */
    VIEW_ALL_BUSINESS_PROFILES: "VIEW_ALL_BUSINESS_PROFILES",
    CREATE_BUSINESS_PROFILE: "CREATE_BUSINESS_PROFILE",
    DELETE_BUSINESS_PROFILE: "DELETE_BUSINESS_PROFILE",
    UPDATE_BUSINESS_PROFILE: "UPDATE_BUSINESS_PROFILE",

    /* TASK related permissions */
    VIEW_TASK_TYPES: "VIEW_TASK_TYPES",
    VIEW_ALL_TASK: "VIEW_ALL_TASK",
    CREATE_TASK: "CREATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    UPDATE_TASK: "UPDATE_TASK",

    /* SPECIFICATION related permissions */
    VIEW_SPECIFICATION_TYPES: "VIEW_SPECIFICATION_TYPES",
    VIEW_ALL_SPECIFICATION: "VIEW_ALL_SPECIFICATION",
    CREATE_SPECIFICATION: "CREATE_SPECIFICATION",
    DELETE_SPECIFICATION: "DELETE_SPECIFICATION",
    UPDATE_SPECIFICATION: "UPDATE_SPECIFICATION",

    /* RUN related permissions */
    RUN_TASK: "RUN_TASK",
}

const DEFAULT_ADMIN_PERMISSIONS: string[] = [
    ...Object.keys(ADMIN_PERMISSIONS)
]

const MONGO_DB_CONNECTION_URL: string = `mongodb+srv://admin:${encodeURIComponent(`@Metropolitan.13`)}@metropolitan.vhiho.mongodb.net/quickchat?retryWrites=true&w=majority&appName=metropolitan`;

const MIN_USERNAME_LENGTH: number = 3;
const MAX_USERNAME_LENGTH: number = 64;

const MIN_PASSWORD_LENGTH: number = 8;
const MAX_PASSWORD_LENGTH: number = 256;

const MIN_NAME_LENGTH: number = 3;
const MAX_NAME_LENGTH: number = 256;

const MIN_EMAIL_LENGTH: number = 3;
const MAX_EMAIL_LENGTH: number = 256;

const MIN_PHONE_LENGTH: number = 7;
const MAX_PHONE_LENGTH: number = 32;

const MIN_PLAN_DETAILS_LENGTH: number = 16;
const MAX_PLAN_DETAILS_LENGTH: number = 2048;

const DEFAULT_ATTEMPTS_LEFT: number = 5;

export {
    ADMIN_PERMISSIONS,
    DEFAULT_ADMIN_PERMISSIONS,
    MONGO_DB_CONNECTION_URL,
    MIN_USERNAME_LENGTH,
    MAX_USERNAME_LENGTH,
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    MIN_NAME_LENGTH,
    MAX_NAME_LENGTH,
    MIN_EMAIL_LENGTH,
    MAX_EMAIL_LENGTH,
    MIN_PHONE_LENGTH,
    MAX_PHONE_LENGTH,
    MIN_PLAN_DETAILS_LENGTH,
    MAX_PLAN_DETAILS_LENGTH,
    DEFAULT_ATTEMPTS_LEFT,
}